### ISSUE TITLE
Are the tile sizes decided independently of what gpu it is rendering on?

### ISSUE THREAD

**Issue by rgkirch** [gregzaal/Auto-Render-Tile-Size#1]
If my gpu has a larger block size then shouldn't it have a larger tile size? I would think that the tile size relates to how many threads the gpu is throwing around. Thanks!

**Comment by gregzaal** [comment]
It's not quite that simple I'm afraid. For example, there have been [reports](https://developer.blender.org/T45093#321102) that the 980ti (and only certain models of it) work best with a tile size of 160x120, which is counter-intuitive considering the number of cores the 980ti has.

There's really no sure-fire way of knowing what the fastest tile size is, the best we can do is make a rough guess.
